name: release

env:
  NODE_VERSION: lts/*

on:
  schedule:
    - cron: "0 9 * * *"
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true
        default: "latest"

permissions:
  contents: write

jobs:
  npm:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment: Release
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
      - run: bun generate --provenance
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          ZIG_VERSION: ${{ github.event.inputs.version }}

